export const STAFF_ROLES = {
  FOUNDER: "FOUNDER",
  CEO: "CEO",
  PLATFORM_ADMIN: "PLATFORM_ADMIN",
  SUPPORT: "SUPPORT",
  OPERATIONS: "OPERATIONS",
  DEVELOPER: "DEVELOPER",
  FINANCE: "FINANCE",
  CUSTOMER_SUCCESS: "CUSTOMER_SUCCESS",
};
